# Generated by Django 5.0.6 on 2026-04-09 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alpages', '0080_proprietaireunitepastorale_delete_upproprietaire'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogementTest',
        ),
    ]
