# Generated by Django 5.0.6 on 2026-04-09 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alpages', '0081_delete_logementtest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuartierUP',
        ),
        migrations.DeleteModel(
            name='Quartieralpage',
        ),
    ]
