# Generated by Django 5.0.6 on 2026-04-09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("alpages", "0082_delete_quartierup_delete_quartieralpage"),
    ]

    operations = [
        migrations.RunSQL(
            sql='DROP TABLE IF EXISTS "alpages_quartieralpage" CASCADE;',
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]