# Generated by Django 5.0.6 on 2026-04-09 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpages', '0083_drop_legacy_quartieralpage_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quartierpasto',
            name='unite_pastorale',
        ),
        migrations.AddField(
            model_name='quartierpasto',
            name='situation_exploitation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quartiers', to='alpages.situationdexploitation'),
        ),
    ]
