# Generated by Django 5.0.6 on 2026-04-10 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alpages', '0084_remove_quartierpasto_unite_pastorale_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TypeCheptel',
        ),
    ]
