# Generated by Django 5.0.6 on 2026-04-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpages', '0086_remove_exploiter_situation_exploitation_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='quartierpasto',
            name='uniq_quartier_id_par_situation',
        ),
        migrations.AddConstraint(
            model_name='quartierpasto',
            constraint=models.UniqueConstraint(fields=('situation_exploitation', 'code_quartier'), name='uniq_code_quartier_par_situation'),
        ),
    ]
