# Generated by Django 5.0.6 on 2026-04-10 10:15

from django.db import migrations
from django.db.models import Q


def forward_backfill(apps, schema_editor):
    Situation = apps.get_model("alpages", "SituationDExploitation")
    Exploiter = apps.get_model("alpages", "Exploiter")
    Cheptel = apps.get_model("alpages", "Cheptel")

    # 1) annee sur SituationDExploitation
    for s in Situation.objects.select_related("unite_pastorale").all().iterator():
        if s.annee is not None:
            continue
        year = None
        if s.date_debut:
            year = s.date_debut.year
        elif s.date_fin:
            year = s.date_fin.year
        elif s.unite_pastorale_id and getattr(s.unite_pastorale, "annee_version", None):
            try:
                year = int(s.unite_pastorale.annee_version)
            except Exception:
                year = None
        if year is not None:
            s.annee = year
            s.save(update_fields=["annee"])

    # 2) situation_exploitation + cheptel sur Exploiter
    qs = Exploiter.objects.select_related("quartier", "cheptel").all()

    for e in qs.iterator():
        changed_fields = []

        # Remplir cheptel si possible
        if e.cheptel_id is None and e.quartier_id and getattr(e.quartier, "situation_exploitation_id", None):
            situation_id = e.quartier.situation_exploitation_id
            cheptels = Cheptel.objects.filter(
                situation_exploitation_id=situation_id
            )

            chosen = None
            cnt = cheptels.count()
            if cnt == 1:
                chosen = cheptels.first()
            elif cnt > 1 and e.date_debut:
                candidates = cheptels.filter(
                    Q(date_debut__isnull=True) | Q(date_debut__lte=e.date_debut),
                    Q(date_fin__isnull=True) | Q(date_fin__gte=e.date_debut),
                )
                if candidates.count() == 1:
                    chosen = candidates.first()

            if chosen is not None:
                e.cheptel_id = chosen.pk
                changed_fields.append("cheptel")

        if changed_fields:
            e.save(update_fields=changed_fields)


def backward_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("alpages", "0087_remove_quartierpasto_uniq_quartier_id_par_situation_and_more"),
    ]

    operations = [
        migrations.RunPython(forward_backfill, backward_noop),
    ]
