# Generated by Django 5.0.6 on 2026-04-23 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpages', '0097_generalize_audit_fields_to_all_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abridurgence',
            options={'verbose_name': "abri d'urgence", 'verbose_name_plural': "abris d'urgence"},
        ),
        migrations.AlterModelOptions(
            name='abridurgencecommodite',
            options={'verbose_name': "abri d'urgence / commodité", 'verbose_name_plural': "abris d'urgence / commodités"},
        ),
        migrations.AlterModelOptions(
            name='beneficierde',
            options={'verbose_name': 'bénéficier de', 'verbose_name_plural': 'bénéficier de'},
        ),
        migrations.AlterModelOptions(
            name='berger',
            options={'verbose_name': 'berger', 'verbose_name_plural': 'bergers'},
        ),
        migrations.AlterModelOptions(
            name='categorie_animaux',
            options={'verbose_name': "catégorie d'animaux", 'verbose_name_plural': "catégories d'animaux"},
        ),
        migrations.AlterModelOptions(
            name='categorie_pension',
            options={'verbose_name': 'catégorie de pension', 'verbose_name_plural': 'catégories de pension'},
        ),
        migrations.AlterModelOptions(
            name='cheptel',
            options={'verbose_name': 'troupeau', 'verbose_name_plural': 'troupeaux'},
        ),
        migrations.AlterModelOptions(
            name='commodite',
            options={'verbose_name': 'commodité', 'verbose_name_plural': 'commodités'},
        ),
        migrations.AlterModelOptions(
            name='conventiondexploitation',
            options={'verbose_name': "convention d'exploitation", 'verbose_name_plural': "conventions d'exploitation"},
        ),
        migrations.AlterModelOptions(
            name='eleveur',
            options={'verbose_name': 'éleveur', 'verbose_name_plural': 'éleveurs'},
        ),
        migrations.AlterModelOptions(
            name='equipementalpage',
            options={'verbose_name': "équipement d'alpage", 'verbose_name_plural': "équipements d'alpage"},
        ),
        migrations.AlterModelOptions(
            name='equipementexploitant',
            options={'verbose_name': "équipement d'exploitant", 'verbose_name_plural': "équipements d'exploitant"},
        ),
        migrations.AlterModelOptions(
            name='espece',
            options={'verbose_name': 'espèce', 'verbose_name_plural': 'espèces'},
        ),
        migrations.AlterModelOptions(
            name='etrecompose',
            options={'verbose_name': "composition d'exploitant", 'verbose_name_plural': "compositions d'exploitant"},
        ),
        migrations.AlterModelOptions(
            name='evenement',
            options={'verbose_name': 'événement', 'verbose_name_plural': 'événements'},
        ),
        migrations.AlterModelOptions(
            name='exploitant',
            options={'verbose_name': 'exploitant', 'verbose_name_plural': 'exploitants'},
        ),
        migrations.AlterModelOptions(
            name='exploiter',
            options={'verbose_name': 'parcours', 'verbose_name_plural': 'parcours'},
        ),
        migrations.AlterModelOptions(
            name='gardesituation',
            options={'verbose_name': 'garde de situation', 'verbose_name_plural': 'gardes de situation'},
        ),
        migrations.AlterModelOptions(
            name='logement',
            options={'verbose_name': 'logement', 'verbose_name_plural': 'logements'},
        ),
        migrations.AlterModelOptions(
            name='logementcommodite',
            options={'verbose_name': 'logement / commodité', 'verbose_name_plural': 'logements / commodités'},
        ),
        migrations.AlterModelOptions(
            name='mesuredeplan',
            options={'verbose_name': 'mesure de plan', 'verbose_name_plural': 'mesures de plan'},
        ),
        migrations.AlterModelOptions(
            name='plandesuivi',
            options={'verbose_name': 'plan de suivi', 'verbose_name_plural': 'plans de suivi'},
        ),
        migrations.AlterModelOptions(
            name='production',
            options={'verbose_name': 'production', 'verbose_name_plural': 'productions'},
        ),
        migrations.AlterModelOptions(
            name='proprietairefoncier',
            options={'verbose_name': 'propriétaire foncier', 'verbose_name_plural': 'propriétaires fonciers'},
        ),
        migrations.AlterModelOptions(
            name='proprietaireunitepastorale',
            options={'verbose_name': 'propriétaire / unité pastorale', 'verbose_name_plural': 'propriétaires / unités pastorales'},
        ),
        migrations.AlterModelOptions(
            name='quartierpasto',
            options={'verbose_name': "quartier d'alpage", 'verbose_name_plural': "quartiers d'alpage"},
        ),
        migrations.AlterModelOptions(
            name='race',
            options={'verbose_name': 'race', 'verbose_name_plural': 'races'},
        ),
        migrations.AlterModelOptions(
            name='ruche',
            options={'verbose_name': 'ruche', 'verbose_name_plural': 'ruches'},
        ),
        migrations.AlterModelOptions(
            name='situationdexploitation',
            options={'verbose_name': "situation d'exploitation", 'verbose_name_plural': "situations d'exploitation"},
        ),
        migrations.AlterModelOptions(
            name='subventionpnv',
            options={'verbose_name': 'subvention PNV', 'verbose_name_plural': 'subventions PNV'},
        ),
        migrations.AlterModelOptions(
            name='type_cheptel',
            options={'verbose_name': 'type de cheptel', 'verbose_name_plural': 'types de cheptel'},
        ),
        migrations.AlterModelOptions(
            name='typeconvention',
            options={'verbose_name': 'type de convention', 'verbose_name_plural': 'types de convention'},
        ),
        migrations.AlterModelOptions(
            name='typedemesure',
            options={'verbose_name': 'type de mesure', 'verbose_name_plural': 'types de mesure'},
        ),
        migrations.AlterModelOptions(
            name='typedesuivi',
            options={'verbose_name': 'type de suivi', 'verbose_name_plural': 'types de suivi'},
        ),
        migrations.AlterModelOptions(
            name='typedexploitant',
            options={'verbose_name': "type d'exploitant", 'verbose_name_plural': "types d'exploitant"},
        ),
        migrations.AlterModelOptions(
            name='typeequipement',
            options={'verbose_name': "type d'équipement", 'verbose_name_plural': "types d'équipement"},
        ),
        migrations.AlterModelOptions(
            name='typeevenement',
            options={'verbose_name': "type d'événement", 'verbose_name_plural': "types d'événement"},
        ),
        migrations.AlterModelOptions(
            name='unitepastorale',
            options={'verbose_name': 'unité pastorale', 'verbose_name_plural': 'unités pastorales'},
        ),
        migrations.RemoveIndex(
            model_name='exploiter',
            name='idx_parcours_quart_date',
        ),
        migrations.RemoveIndex(
            model_name='exploiter',
            name='idx_parcours_chept_date',
        ),
        migrations.RemoveIndex(
            model_name='quartierpasto',
            name='idx_quartier_situation',
        ),
        migrations.RemoveIndex(
            model_name='situationdexploitation',
            name='idx_situation_up_annee',
        ),
        migrations.AlterField(
            model_name='abridurgencecommodite',
            name='abri_urgence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commodites', to='alpages.abridurgence'),
        ),
        migrations.AlterField(
            model_name='abridurgencecommodite',
            name='commodite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='abris_urgence', to='alpages.commodite'),
        ),
        migrations.AlterField(
            model_name='beneficierde',
            name='abri_urgence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='beneficiaires', to='alpages.abridurgence'),
        ),
        migrations.AlterField(
            model_name='beneficierde',
            name='exploitant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='beneficiaires', to='alpages.exploitant'),
        ),
        migrations.AlterField(
            model_name='categorie_animaux',
            name='espece',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categories_animaux', to='alpages.espece'),
        ),
        migrations.AlterField(
            model_name='cheptel',
            name='eleveur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cheptels', to='alpages.eleveur'),
        ),
        migrations.AlterField(
            model_name='cheptel',
            name='situation_exploitation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cheptels', to='alpages.situationdexploitation'),
        ),
        migrations.AlterField(
            model_name='cheptel',
            name='type_cheptel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cheptels', to='alpages.type_cheptel'),
        ),
        migrations.AlterField(
            model_name='conventiondexploitation',
            name='exploitant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conventions', to='alpages.exploitant'),
        ),
        migrations.AlterField(
            model_name='conventiondexploitation',
            name='type_convention',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conventions', to='alpages.typeconvention'),
        ),
        migrations.AlterField(
            model_name='conventiondexploitation',
            name='unite_pastorale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conventions', to='alpages.unitepastorale'),
        ),
        migrations.AlterField(
            model_name='equipementalpage',
            name='type_equipement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eqptsAlpage', to='alpages.typeequipement'),
        ),
        migrations.AlterField(
            model_name='equipementalpage',
            name='unite_pastorale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eqptsAlpage', to='alpages.unitepastorale'),
        ),
        migrations.AlterField(
            model_name='equipementexploitant',
            name='situation_exploitation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eqptsExploitant', to='alpages.situationdexploitation'),
        ),
        migrations.AlterField(
            model_name='equipementexploitant',
            name='type_equipement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eqptsExploitant', to='alpages.typeequipement'),
        ),
        migrations.AlterField(
            model_name='etrecompose',
            name='eleveur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='alpages.eleveur'),
        ),
        migrations.AlterField(
            model_name='etrecompose',
            name='exploitant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='alpages.exploitant'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='mesure_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evenements', to='alpages.mesuredeplan'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='type_evenement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evenements', to='alpages.typeevenement'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='unite_pastorale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evenements', to='alpages.unitepastorale'),
        ),
        migrations.AlterField(
            model_name='exploitant',
            name='president',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exploitants', to='alpages.eleveur'),
        ),
        migrations.AlterField(
            model_name='exploitant',
            name='type_exploitant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exploitants', to='alpages.typedexploitant'),
        ),
        migrations.AlterField(
            model_name='exploiter',
            name='cheptel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parcours', to='alpages.cheptel'),
        ),
        migrations.AlterField(
            model_name='exploiter',
            name='date_fin',
            field=models.DateField(default='2099-12-31'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exploiter',
            name='quartier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parcours', to='alpages.quartierpasto'),
        ),
        migrations.AlterField(
            model_name='gardesituation',
            name='berger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gardes_situation', to='alpages.berger'),
        ),
        migrations.AlterField(
            model_name='gardesituation',
            name='situation_exploitation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gardes_situation', to='alpages.situationdexploitation'),
        ),
        migrations.AlterField(
            model_name='logement',
            name='unite_pastorale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='logements', to='alpages.unitepastorale'),
        ),
        migrations.AlterField(
            model_name='logementcommodite',
            name='commodite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='logements', to='alpages.commodite'),
        ),
        migrations.AlterField(
            model_name='logementcommodite',
            name='logement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commodites', to='alpages.logement'),
        ),
        migrations.AlterField(
            model_name='mesuredeplan',
            name='plan_suivi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mesures_de_plan', to='alpages.plandesuivi'),
        ),
        migrations.AlterField(
            model_name='mesuredeplan',
            name='type_mesure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mesures_de_plan', to='alpages.typedemesure'),
        ),
        migrations.AlterField(
            model_name='plandesuivi',
            name='type_suivi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plans_de_suivi', to='alpages.typedesuivi'),
        ),
        migrations.AlterField(
            model_name='plandesuivi',
            name='unite_pastorale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plans_de_suivi', to='alpages.unitepastorale'),
        ),
        migrations.AlterField(
            model_name='proprietaireunitepastorale',
            name='proprietaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unites_pastorales_proprietaire', to='alpages.proprietairefoncier'),
        ),
        migrations.AlterField(
            model_name='proprietaireunitepastorale',
            name='unite_pastorale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proprietaires_unite_pastorale', to='alpages.unitepastorale'),
        ),
        migrations.AlterField(
            model_name='quartierpasto',
            name='situation_exploitation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quartiers', to='alpages.situationdexploitation'),
        ),
        migrations.AlterField(
            model_name='race',
            name='espece',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='races', to='alpages.espece'),
        ),
        migrations.AlterField(
            model_name='ruche',
            name='situation_exploitation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ruches', to='alpages.situationdexploitation'),
        ),
        migrations.AlterField(
            model_name='subventionpnv',
            name='exploitant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subventions', to='alpages.exploitant'),
        ),
        migrations.AlterField(
            model_name='type_cheptel',
            name='categorie_animaux',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='types_cheptel', to='alpages.categorie_animaux'),
        ),
        migrations.AlterField(
            model_name='type_cheptel',
            name='pension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='types_cheptel', to='alpages.categorie_pension'),
        ),
        migrations.AlterField(
            model_name='type_cheptel',
            name='production',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='types_cheptel', to='alpages.production'),
        ),
        migrations.AlterField(
            model_name='type_cheptel',
            name='race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='types_cheptel', to='alpages.race'),
        ),
        migrations.AddConstraint(
            model_name='beneficierde',
            constraint=models.CheckConstraint(check=models.Q(('date_fin__isnull', True), ('date_debut__lte', models.F('date_fin')), _connector='OR'), name='chk_beneficier_de_dates_coherentes'),
        ),
        migrations.AddConstraint(
            model_name='cheptel',
            constraint=models.CheckConstraint(check=models.Q(('date_fin__isnull', True), ('date_debut__lte', models.F('date_fin')), _connector='OR'), name='chk_cheptel_dates_coherentes'),
        ),
        migrations.AddConstraint(
            model_name='conventiondexploitation',
            constraint=models.CheckConstraint(check=models.Q(('date_fin__isnull', True), ('date_debut__lte', models.F('date_fin')), _connector='OR'), name='chk_convention_dates_coherentes'),
        ),
        migrations.AddConstraint(
            model_name='gardesituation',
            constraint=models.CheckConstraint(check=models.Q(('date_fin__isnull', True), ('date_debut__lte', models.F('date_fin')), _connector='OR'), name='chk_garde_situation_dates_coherentes'),
        ),
    ]
