# Generated by Django 5.0.6 on 2026-04-26 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alpages', '0098_alter_abridurgence_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categorie_animaux',
            table='alpages_categorie_animaux',
        ),
        migrations.AlterModelTable(
            name='categorie_pension',
            table='alpages_categorie_pension',
        ),
        migrations.AlterModelTable(
            name='type_cheptel',
            table='alpages_type_cheptel',
        ),
    ]
