# Generated by Django 5.0.6 on 2026-04-26 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alpages', '0099_fix_db_table_snake_case_models'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorie_animaux',
            new_name='CategorieAnimaux',
        ),
        migrations.RenameModel(
            old_name='Categorie_pension',
            new_name='CategoriePension',
        ),
        migrations.RenameModel(
            old_name='Type_cheptel',
            new_name='TypeCheptel',
        ),
    ]
