# Generated by Django 5.0.6 on 2026-05-07 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpages', '0105_auto_pk_wave3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenement',
            name='unite_pastorale',
        ),
        migrations.AddField(
            model_name='evenement',
            name='situation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evenements', to='alpages.situationdexploitation'),
        ),
    ]
