# Generated by Django 5.0.6 on 2026-05-11 07:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpages', '0106_remove_evenement_unite_pastorale_evenement_situation'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheptel',
            name='categorie_animaux',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cheptels', to='alpages.categorieanimaux'),
        ),
        migrations.AddField(
            model_name='cheptel',
            name='coefficient_UGB',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='cheptel',
            name='pension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cheptels', to='alpages.categoriepension'),
        ),
        migrations.AddField(
            model_name='cheptel',
            name='production',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cheptels', to='alpages.production'),
        ),
        migrations.AddField(
            model_name='cheptel',
            name='race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cheptels', to='alpages.race'),
        ),
    ]
