# Generated by Django 5.0.6 on 2026-05-11 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alpages', '0107_add_cheptel_fields_ugb_race_production'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cheptel',
            name='type_cheptel',
        ),
        migrations.DeleteModel(
            name='TypeCheptel',
        ),
    ]
