# Generated by Django 5.0.6 on 2026-05-11 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alpages', '0108_remove_typecheptel_model_and_fk'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogementCommodite',
        ),
    ]
