# Generated by Django 5.0.6 on 2026-05-13 09:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alpages", "0111_equipement_exploitant_link_beneficierde"),
    ]

    operations = [
        migrations.AddField(
            model_name="categorieanimaux",
            name="coefficient_UGB",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1),
                ],
            ),
        ),
    ]
