# Generated by Django 5.0.6 on 2026-05-18 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alpages", "0113_mesuredeplan_geometry"),
    ]

    operations = [
        migrations.CreateModel(
            name="RealisationMesure",
            fields=[
                ("created_by", models.CharField(blank=True, max_length=150, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("modified_on", models.DateTimeField(blank=True, null=True)),
                (
                    "id_realisation_mesure",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("non_realisee", "Non réalisée"),
                            ("partielle", "Partiellement réalisée"),
                            ("realisee", "Réalisée"),
                        ],
                        default="non_realisee",
                        max_length=20,
                    ),
                ),
                ("commentaire", models.TextField(blank=True, null=True)),
                ("date_realisation", models.DateField(blank=True, null=True)),
                (
                    "mesure_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="realisations",
                        to="alpages.mesuredeplan",
                    ),
                ),
                (
                    "situation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="realisations_mesures",
                        to="alpages.situationdexploitation",
                    ),
                ),
            ],
            options={
                "verbose_name": "réalisation de mesure",
                "verbose_name_plural": "réalisations de mesures",
                "unique_together": {("mesure_plan", "situation")},
            },
        ),
    ]
