# Generated by Django 5.0.6 on 2026-05-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alpages", "0116_remove_up_annee_version_situation_annee_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="unitepastorale",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
