# Generated by Django 5.0.6 on 2026-05-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alpages", "0117_up_active_field"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="geometrieunitepastorale",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("date_fin_validite__isnull", True),
                    ("date_debut_validite__lte", models.F("date_fin_validite")),
                    _connector="OR",
                ),
                name="chk_geometrie_up_dates_coherentes",
            ),
        ),
    ]
