# Generated by Django 5.0.6 on 2026-05-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alpages", "0118_chk_geometrie_up_dates_coherentes"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="mesuredeplan",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("fin_periode__isnull", True),
                    ("debut_periode__lte", models.F("fin_periode")),
                    _connector="OR",
                ),
                name="chk_mesure_plan_periodes_coherentes",
            ),
        ),
        migrations.AddConstraint(
            model_name="plandesuivi",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("date_fin__isnull", True),
                    ("date_debut__lte", models.F("date_fin")),
                    _connector="OR",
                ),
                name="chk_plan_suivi_dates_coherentes",
            ),
        ),
    ]
