# Generated by Django 5.0.6 on 2026-05-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alpages", "0120_chk_convention_periodes_exploitation_coherentes"),
    ]

    operations = [
        migrations.AddField(
            model_name="mesuredeplan",
            name="obligation",
            field=models.BooleanField(default=False),
        ),
    ]
