name: 🧩 Task
description: Tâche technique
title: "[Task] "
labels: ["task"]

body:
  - type: textarea
    id: description
    attributes:
      label: 🎯 Description
      placeholder: Décris la tâche
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: 🔧 Détails techniques
      placeholder: Backend / Frontend

  - type: input
    id: parent
    attributes:
      label: 🔗 Issue parent
      placeholder: "#12"

  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ À faire
      options:
        - label: Implémentation
        - label: Test
        - label: Validation