# Generated by Django 5.0.6 on 2026-05-31 18:11

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AbriDUrgence",
            fields=[
                ("created_by", models.CharField(blank=True, max_length=150, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("modified_on", models.DateTimeField(blank=True, null=True)),
                (
                    "id_abri_urgence",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("description", models.CharField(max_length=50)),
                ("etat", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "abri d'urgence",
                "verbose_name_plural": "abris d'urgence",
            },
        ),
        migrations.CreateModel(
            name="Berger",
            fields=[
                ("created_by", models.CharField(blank=True, max_length=150, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("modified_on", models.DateTimeField(blank=True, null=True)),
                ("id_berger", models.BigAutoField(primary_key=True, serialize=False)),
                ("nom_berger", models.CharField(max_length=50)),
                ("prenom_berger", models.CharField(max_length=50)),
                ("tel_berger", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "adresse_berger",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "commentaire",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
            ],
            options={
                "verbose_name": "berger",
                "verbose_name_plural": "bergers",
            },
        ),
        migrations.CreateModel(
            name="CategoriePension",
            fields=[
                ("created_by", models.CharField(blank=True, max_length=150, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("modified_on", models.DateTimeField(blank=True, null=True)),
                (
                    "id_categorie_pension",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("description", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "catégorie de pension",
                "verbose_name_plural": "catégories de pension",
            },
        ),
        migrations.CreateModel(
            name="Commodite",
            fields=[
                ("created_by", models.CharField(blank=True, max_length=150, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("modified_on", models.DateTimeField(blank=True, null=True)),
                (
                    "id_commodite",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("description", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "commodité",
                "verbose_name_plural": "commodités",
            },
        ),
        migrations.CreateModel(
            name="Eleveur",
            fields=[
                ("created_by", models.CharField(blank=True, max_length=150, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("modified_on", models.DateTimeField(blank=True, null=True)),
                ("id_eleveur", models.AutoField(primary_key=True, serialize=False)),
                ("nom_eleveur", models.CharField(max_length=50)),
                (
                    "prenom_eleveur",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("tel_eleveur", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "mail_eleveur",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "adresse_eleveur",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "commentaire",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
            ],
            options={
                "verbose_name": "éleveur",
                "verbose_name_plural": "éleveurs",
            },
        ),
        migrations.CreateModel(
            name="Espece",
            fields=[
                ("created_by", models.CharField(blank=True, max_length=150, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("modified_on", models.DateTimeField(blank=True, null=True)),
                ("id_espece", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "espèce",
                "verbose_name_plural": "espèces",
            },
        ),
        migrations.CreateModel(
            name="PlanDeSuivi",
            fields=[
                ("created_by", models.CharField(blank=True, max_length=150, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("modified_on", models.DateTimeField(blank=True, null=True)),
                (
                    "id_plan_suivi",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("description", models.CharField(max_length=50)),
                ("date_debut", models.DateField(blank=True, null=True)),
                ("date_fin", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "plan de suivi",
                "verbose_name_plural": "plans de suivi",
            },
        ),
        migrations.CreateModel(
            name="Production",
            fields=[
                ("created_by", models.CharField(blank=True, max_length=150, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("modified_on", models.DateTimeField(blank=True, null=True)),
                ("id_production", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "production",
                "verbose_name_plural": "productions",
            },
        ),
        migrations.CreateModel(
            name="ProprietaireFoncier",
            fields=[
                ("created_by", models.CharField(blank=True, max_length=150, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("modified_on", models.DateTimeField(blank=True, null=True)),
                (
                    "id_proprietaire",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("nom_propr", models.CharField(max_length=50)),
                (
                    "prenom_propr",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("tel_propr", models.CharField(blank=True, max_length=30, null=True)),
                ("mail_propr", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "adresse_propr",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("commentaire", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "verbose_name": "propriétaire foncier",
                "verbose_name_plural": "propriétaires fonciers",
            },
        ),
        migrations.CreateModel(
            name="QuartierPasto",
            fields=[
                ("created_by", models.CharField(blank=True, max_length=150, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("modified_on", models.DateTimeField(blank=True, null=True)),
                ("id_quartier", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "code_quartier",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "nom_quartier",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True, null=True, srid=2154
                    ),
                ),
            ],
            options={
                "verbose_name": "quartier d'alpage",
                "verbose_name_plural": "quartiers d'alpage",
            },
        ),
        migrations.CreateModel(
            name="TypeConvention",
            fields=[
                ("created_by", models.CharField(blank=True, max_length=150, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("modified_on", models.DateTimeField(blank=True, null=True)),
                (
                    "id_type_convention",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("description", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "type de convention",
                "verbose_name_plural": "types de convention",
            },
        ),
        migrations.CreateModel(
            name="TypeDeMesure",
            fields=[
                ("created_by", models.CharField(blank=True, max_length=150, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("modified_on", models.DateTimeField(blank=True, null=True)),
                ("id_type_mesure", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "type de mesure",
                "verbose_name_plural": "types de mesure",
            },
        ),
        migrations.CreateModel(
            name="TypeDeSuivi",
            fields=[
                ("created_by", models.CharField(blank=True, max_length=150, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("modified_on", models.DateTimeField(blank=True, null=True)),
                ("id_type_suivi", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "type de suivi",
                "verbose_name_plural": "types de suivi",
            },
        ),
        migrations.CreateModel(
            name="TypeDExploitant",
            fields=[
                ("created_by", models.CharField(blank=True, max_length=150, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("modified_on", models.DateTimeField(blank=True, null=True)),
                (
                    "id_type_exploitant",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("description", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "type d'exploitant",
                "verbose_name_plural": "types d'exploitant",
            },
        ),
        migrations.CreateModel(
            name="TypeEquipement",
            fields=[
                ("created_by", models.CharField(blank=True, max_length=150, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("modified_on", models.DateTimeField(blank=True, null=True)),
                (
                    "id_type_equipement",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("description", models.CharField(max_length=50)),
                ("categorie", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "type d'équipement",
                "verbose_name_plural": "types d'équipement",
            },
        ),
        migrations.CreateModel(
            name="TypeEvenement",
            fields=[
                ("created_by", models.CharField(blank=True, max_length=150, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("modified_on", models.DateTimeField(blank=True, null=True)),
                (
                    "id_type_evenement",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("description", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "type d'événement",
                "verbose_name_plural": "types d'événement",
            },
        ),
        migrations.CreateModel(
            name="UnitePastorale",
            fields=[
                ("created_by", models.CharField(blank=True, max_length=150, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("modified_on", models.DateTimeField(blank=True, null=True)),
                (
                    "id_unite_pastorale",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("code_up", models.CharField(max_length=50)),
                ("nom_up", models.CharField(max_length=50)),
                (
                    "geom_active",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=2154
                    ),
                ),
                ("secteur", models.CharField(blank=True, max_length=50, null=True)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "unité pastorale",
                "verbose_name_plural": "unités pastorales",
            },
        ),
        migrations.CreateModel(
            name="AbriDUrgenceCommodite",
            fields=[
                ("created_by", models.CharField(blank=True, max_length=150, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("modified_on", models.DateTimeField(blank=True, null=True)),
                (
                    "id_abri_urgence_commodite",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("etat", models.CharField(max_length=50)),
                ("commentaire", models.CharField(blank=True, max_length=50, null=True)),
                ("quantite", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "abri_urgence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commodites",
                        to="suivi_pasto.abridurgence",
                    ),
                ),
                (
                    "commodite",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="abris_urgence",
                        to="suivi_pasto.commodite",
                    ),
                ),
            ],
            options={
                "verbose_name": "abri d'urgence / commodité",
                "verbose_name_plural": "abris d'urgence / commodités",
            },
        ),
        migrations.CreateModel(
            name="CategorieAnimaux",
            fields=[
                ("created_by", models.CharField(blank=True, max_length=150, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("modified_on", models.DateTimeField(blank=True, null=True)),
                (
                    "id_categorie_animaux",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("description", models.CharField(max_length=50)),
                (
                    "coefficient_UGB",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "espece",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="categories_animaux",
                        to="suivi_pasto.espece",
                    ),
                ),
            ],
            options={
                "verbose_name": "catégorie d'animaux",
                "verbose_name_plural": "catégories d'animaux",
            },
        ),
        migrations.CreateModel(
            name="Exploitant",
            fields=[
                ("created_by", models.CharField(blank=True, max_length=150, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("modified_on", models.DateTimeField(blank=True, null=True)),
                ("id_exploitant", models.AutoField(primary_key=True, serialize=False)),
                ("nom_exploitant", models.CharField(max_length=50)),
                (
                    "president",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exploitants",
                        to="suivi_pasto.eleveur",
                    ),
                ),
                (
                    "type_exploitant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exploitants",
                        to="suivi_pasto.typedexploitant",
                    ),
                ),
            ],
            options={
                "verbose_name": "exploitant",
                "verbose_name_plural": "exploitants",
            },
        ),
        migrations.CreateModel(
            name="EtreCompose",
            fields=[
                ("created_by", models.CharField(blank=True, max_length=150, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("modified_on", models.DateTimeField(blank=True, null=True)),
                (
                    "id_etre_compose",
                    models.BigAutoField(
                        db_column="id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "eleveur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="suivi_pasto.eleveur",
                    ),
                ),
                (
                    "exploitant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="compositions",
                        to="suivi_pasto.exploitant",
                    ),
                ),
                (
                    "exploitant_membre",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_exploitant_membre",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to="suivi_pasto.exploitant",
                    ),
                ),
            ],
            options={
                "verbose_name": "composition d'exploitant",
                "verbose_name_plural": "compositions d'exploitant",
            },
        ),
        migrations.CreateModel(
            name="Cheptel",
            fields=[
                ("created_by", models.CharField(blank=True, max_length=150, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("modified_on", models.DateTimeField(blank=True, null=True)),
                ("id_cheptel", models.BigAutoField(primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=50)),
                ("nombre_animaux", models.IntegerField()),
                ("date_debut", models.DateField(blank=True, null=True)),
                ("date_fin", models.DateField(blank=True, null=True)),
                (
                    "coefficient_UGB",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "categorie_animaux",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cheptels",
                        to="suivi_pasto.categorieanimaux",
                    ),
                ),
                (
                    "pension",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cheptels",
                        to="suivi_pasto.categoriepension",
                    ),
                ),
                (
                    "eleveur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cheptels",
                        to="suivi_pasto.eleveur",
                    ),
                ),
                (
                    "exploitant_proprietaire",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_exploitant_proprietaire",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cheptels_proprietaire",
                        to="suivi_pasto.exploitant",
                    ),
                ),
                (
                    "production",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cheptels",
                        to="suivi_pasto.production",
                    ),
                ),
            ],
            options={
                "verbose_name": "troupeau",
                "verbose_name_plural": "troupeaux",
            },
        ),
        migrations.CreateModel(
            name="BeneficierDe",
            fields=[
                ("created_by", models.CharField(blank=True, max_length=150, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("modified_on", models.DateTimeField(blank=True, null=True)),
                (
                    "id_beneficier_de",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField(blank=True, null=True)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=2154
                    ),
                ),
                (
                    "abri_urgence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="beneficiaires",
                        to="suivi_pasto.abridurgence",
                    ),
                ),
                (
                    "exploitant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="beneficiaires",
                        to="suivi_pasto.exploitant",
                    ),
                ),
            ],
            options={
                "verbose_name": "bénéficier de",
                "verbose_name_plural": "bénéficier de",
            },
        ),
        migrations.CreateModel(
            name="MesureDePlan",
            fields=[
                ("created_by", models.CharField(blank=True, max_length=150, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("modified_on", models.DateTimeField(blank=True, null=True)),
                (
                    "id_mesure_plan",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("description", models.CharField(max_length=50)),
                ("commentaire", models.CharField(blank=True, max_length=50, null=True)),
                ("debut_periode", models.DateField(blank=True, null=True)),
                ("fin_periode", models.DateField(blank=True, null=True)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True, null=True, srid=2154
                    ),
                ),
                ("obligation", models.BooleanField(default=False)),
                (
                    "plan_suivi",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mesures_de_plan",
                        to="suivi_pasto.plandesuivi",
                    ),
                ),
                (
                    "type_mesure",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mesures_de_plan",
                        to="suivi_pasto.typedemesure",
                    ),
                ),
            ],
            options={
                "verbose_name": "mesure de plan",
                "verbose_name_plural": "mesures de plan",
            },
        ),
        migrations.CreateModel(
            name="Exploiter",
            fields=[
                ("created_by", models.CharField(blank=True, max_length=150, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("modified_on", models.DateTimeField(blank=True, null=True)),
                (
                    "id_exploiter",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField()),
                (
                    "nombre_animaux",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "mode_conduite",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "commentaire",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "cheptel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parcours",
                        to="suivi_pasto.cheptel",
                    ),
                ),
                (
                    "quartier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parcours",
                        to="suivi_pasto.quartierpasto",
                    ),
                ),
            ],
            options={
                "verbose_name": "parcours",
                "verbose_name_plural": "parcours",
            },
        ),
        migrations.CreateModel(
            name="Race",
            fields=[
                ("created_by", models.CharField(blank=True, max_length=150, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("modified_on", models.DateTimeField(blank=True, null=True)),
                ("id_race", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=50)),
                (
                    "espece",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="races",
                        to="suivi_pasto.espece",
                    ),
                ),
            ],
            options={
                "verbose_name": "race",
                "verbose_name_plural": "races",
            },
        ),
        migrations.AddField(
            model_name="cheptel",
            name="race",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cheptels",
                to="suivi_pasto.race",
            ),
        ),
        migrations.CreateModel(
            name="SituationDExploitation",
            fields=[
                ("created_by", models.CharField(blank=True, max_length=150, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("modified_on", models.DateTimeField(blank=True, null=True)),
                (
                    "id_situation",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("nom_situation", models.CharField(max_length=150)),
                ("date_debut", models.DateField(blank=True, null=True)),
                ("date_fin", models.DateField(blank=True, null=True)),
                (
                    "exploitant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="situations",
                        to="suivi_pasto.exploitant",
                    ),
                ),
                (
                    "unite_pastorale",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="situations",
                        to="suivi_pasto.unitepastorale",
                    ),
                ),
            ],
            options={
                "verbose_name": "situation d'exploitation",
                "verbose_name_plural": "situations d'exploitation",
            },
        ),
        migrations.CreateModel(
            name="Ruche",
            fields=[
                ("created_by", models.CharField(blank=True, max_length=150, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("modified_on", models.DateTimeField(blank=True, null=True)),
                ("id_ruche", models.BigAutoField(primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=50)),
                ("geometry", django.contrib.gis.db.models.fields.PointField(srid=2154)),
                (
                    "situation_exploitation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ruches",
                        to="suivi_pasto.situationdexploitation",
                    ),
                ),
            ],
            options={
                "verbose_name": "ruche",
                "verbose_name_plural": "ruches",
            },
        ),
        migrations.CreateModel(
            name="RealisationMesure",
            fields=[
                ("created_by", models.CharField(blank=True, max_length=150, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("modified_on", models.DateTimeField(blank=True, null=True)),
                (
                    "id_realisation_mesure",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("non_realisee", "Non réalisée"),
                            ("partielle", "Partiellement réalisée"),
                            ("realisee", "Réalisée"),
                        ],
                        default="non_realisee",
                        max_length=20,
                    ),
                ),
                ("commentaire", models.TextField(blank=True, null=True)),
                ("date_realisation", models.DateField(blank=True, null=True)),
                (
                    "mesure_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="realisations",
                        to="suivi_pasto.mesuredeplan",
                    ),
                ),
                (
                    "situation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="realisations_mesures",
                        to="suivi_pasto.situationdexploitation",
                    ),
                ),
            ],
            options={
                "verbose_name": "réalisation de mesure",
                "verbose_name_plural": "réalisations de mesures",
            },
        ),
        migrations.AddField(
            model_name="quartierpasto",
            name="situation_exploitation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quartiers",
                to="suivi_pasto.situationdexploitation",
            ),
        ),
        migrations.CreateModel(
            name="GardeSituation",
            fields=[
                ("created_by", models.CharField(blank=True, max_length=150, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("modified_on", models.DateTimeField(blank=True, null=True)),
                (
                    "id_garde_situation",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField(blank=True, null=True)),
                (
                    "commentaire",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "berger",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gardes_situation",
                        to="suivi_pasto.berger",
                    ),
                ),
                (
                    "situation_exploitation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gardes_situation",
                        to="suivi_pasto.situationdexploitation",
                    ),
                ),
            ],
            options={
                "verbose_name": "garde de situation",
                "verbose_name_plural": "gardes de situation",
            },
        ),
        migrations.AddField(
            model_name="cheptel",
            name="situation_exploitation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cheptels",
                to="suivi_pasto.situationdexploitation",
            ),
        ),
        migrations.CreateModel(
            name="SubventionPNV",
            fields=[
                ("created_by", models.CharField(blank=True, max_length=150, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("modified_on", models.DateTimeField(blank=True, null=True)),
                (
                    "id_subvention",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("description", models.CharField(max_length=50)),
                ("montant", models.DecimalField(decimal_places=2, max_digits=15)),
                ("engage", models.BooleanField(default=False)),
                ("paye", models.BooleanField(default=False)),
                (
                    "exploitant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subventions",
                        to="suivi_pasto.exploitant",
                    ),
                ),
            ],
            options={
                "verbose_name": "subvention PNV",
                "verbose_name_plural": "subventions PNV",
            },
        ),
        migrations.AddField(
            model_name="plandesuivi",
            name="type_suivi",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="plans_de_suivi",
                to="suivi_pasto.typedesuivi",
            ),
        ),
        migrations.CreateModel(
            name="EquipementExploitant",
            fields=[
                ("created_by", models.CharField(blank=True, max_length=150, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("modified_on", models.DateTimeField(blank=True, null=True)),
                (
                    "id_equipement_exploitant",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("description", models.CharField(max_length=150)),
                ("etat", models.CharField(max_length=50)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True, null=True, srid=2154
                    ),
                ),
                (
                    "beneficier_de",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="equipement",
                        to="suivi_pasto.beneficierde",
                    ),
                ),
                (
                    "situation_exploitation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="eqptsExploitant",
                        to="suivi_pasto.situationdexploitation",
                    ),
                ),
                (
                    "type_equipement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="eqptsExploitant",
                        to="suivi_pasto.typeequipement",
                    ),
                ),
            ],
            options={
                "verbose_name": "équipement d'exploitant",
                "verbose_name_plural": "équipements d'exploitant",
            },
        ),
        migrations.CreateModel(
            name="Evenement",
            fields=[
                ("created_by", models.CharField(blank=True, max_length=150, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("modified_on", models.DateTimeField(blank=True, null=True)),
                (
                    "id_evenement",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("date_evenement", models.DateField()),
                ("observateur", models.CharField(max_length=50)),
                ("date_observation", models.DateField()),
                ("source", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True, null=True, srid=2154
                    ),
                ),
                (
                    "mesure_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evenements",
                        to="suivi_pasto.mesuredeplan",
                    ),
                ),
                (
                    "situation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evenements",
                        to="suivi_pasto.situationdexploitation",
                    ),
                ),
                (
                    "type_evenement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evenements",
                        to="suivi_pasto.typeevenement",
                    ),
                ),
            ],
            options={
                "verbose_name": "événement",
                "verbose_name_plural": "événements",
            },
        ),
        migrations.CreateModel(
            name="ProprietaireUnitePastorale",
            fields=[
                ("created_by", models.CharField(blank=True, max_length=150, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("modified_on", models.DateTimeField(blank=True, null=True)),
                (
                    "id_proprietaire_up",
                    models.BigAutoField(
                        db_column="id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "proprietaire",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="unites_pastorales_proprietaire",
                        to="suivi_pasto.proprietairefoncier",
                    ),
                ),
                (
                    "unite_pastorale",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="proprietaires_unite_pastorale",
                        to="suivi_pasto.unitepastorale",
                    ),
                ),
            ],
            options={
                "verbose_name": "propriétaire / unité pastorale",
                "verbose_name_plural": "propriétaires / unités pastorales",
            },
        ),
        migrations.AddField(
            model_name="plandesuivi",
            name="unite_pastorale",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="plans_de_suivi",
                to="suivi_pasto.unitepastorale",
            ),
        ),
        migrations.CreateModel(
            name="Logement",
            fields=[
                ("created_by", models.CharField(blank=True, max_length=150, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("modified_on", models.DateTimeField(blank=True, null=True)),
                (
                    "id_logement",
                    models.BigAutoField(
                        db_column="id", primary_key=True, serialize=False
                    ),
                ),
                ("logement_code", models.CharField(max_length=10)),
                (
                    "nom_logement",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "statut",
                    models.CharField(
                        blank=True,
                        choices=[("existant", "existant"), ("besoin", "besoin")],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "acces_final",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("carrossable", "carrossable"),
                            ("4_4", "4*4"),
                            ("quad", "quad"),
                            ("pedestre", "pédestre"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "propriete",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("communal", "communal"),
                            ("domanial", "domanial"),
                            ("prive", "privé"),
                            ("afp", "afp"),
                            ("gp", "gp"),
                            ("departemental", "départemental"),
                            ("domaine_skiable", "domaine skiable"),
                            ("autre collectivité", "autre collectivité"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "type_logement",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("logement_principal", "logement principal"),
                            ("logement_secondaire", "logement secondaire"),
                            ("abri_sommaire", "abri sommaire"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "multiusage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("uniquement_pastoral", "uniquement pastoral"),
                            ("abri_randonneurs", "abri randonneurs"),
                            ("refuge_garde", "refuge gardé"),
                            ("resto_station_ski", "resto station ski"),
                            ("poste_de_secours", "poste de secours"),
                            ("autre", "autre"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "activite_laitiere",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("salle_de_traite", "salle de traite"),
                            ("salle_de_transformation", "salle de transformation"),
                            ("les_deux", "les deux"),
                            ("aucune", "aucune"),
                            ("inconnu", "inconnu"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "etat_batiment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("bon", "bon"),
                            ("moyen", "moyen"),
                            ("delabre", "délabré"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "accueil_public",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("aucun_accueil", "aucun accueil du public"),
                            ("accueil_ss_vente", "accueil du public sans vente"),
                            ("accueil_vente", "accueil et vente au public"),
                            ("vente_ss_accueil", "vente sans accueil du public"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "mixite_possible",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("oui", "oui"),
                            ("non", "non"),
                            ("inconnu", "inconnu"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "surface_logement",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("inf14", "< 14 m2"),
                            ("sup14_inf20", "[14 - 20] m2"),
                            ("sup20_inf40", "]20 - 40] m2"),
                            ("sup40_inf80", "]40 - 80] m2"),
                            ("sup80", "> 80 m2"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "presence_douche",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("oui", "oui"),
                            ("non", "non"),
                            ("inconnu", "inconnu"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "type_wc",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("toilettes_seches", "toilettes sèches"),
                            ("classique", "classique"),
                            ("absence", "absence"),
                            ("inconnu", "inconnu"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "alim_elec",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mini_renouv", "mini renouvelable"),
                            ("renouv_inter", "renouvelable intermédiaire"),
                            ("gros_renouv", "gros renouvelable"),
                            ("reseau_public", "réseau public"),
                            ("groupe_elec", "groupe électrogène"),
                            ("absence", "absence"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "alim_eau",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("interieur", "intérieur"),
                            ("ext_inf50", "extérieur < 50m"),
                            ("ext_sup50", "extérieur > 50 m"),
                            ("absence", "absence"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "origine_eau",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("source_captee", "source captée"),
                            ("eau_de_surface", "eau de surface"),
                            ("impluvium", "impluvium"),
                            ("recup_toiture", "récupération toiture"),
                            ("reseau", "réseau"),
                            ("transport", "transport"),
                            ("absence", "absence"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "qualite_eau",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("non_consommee", "non consommée"),
                            ("eau_consommee", "eau consommée"),
                            ("eau_traitee", "eau traitée"),
                            ("eau_regl_potable", "eau réglementairement potable"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "dispo_eau",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("a_volonte", "à volonté"),
                            ("irregulier", "irrégulier"),
                            ("absence", "absence"),
                            ("inconnnu", "inconnu"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "assainissement",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("puits_perdu", "puits perdu"),
                            ("fosse_septique", "fosse septique"),
                            ("tout à l'égoût", "tout à l'égoût"),
                            ("bassin_trt", "bassin de traitement"),
                            ("champ_epandage", "champ d'épandage"),
                            ("absence", "absence"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "chauffe_eau",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("chauffe_eau_gaz", "chauffe-eau gaz"),
                            ("chauffe_eau_elec", "chauffe-eau électrique"),
                            ("poele_bois", "poêle bouilleur au bois"),
                            ("chauffe_eau_solaire", "chauffe-eau solaire"),
                            ("absence", "absence"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "chauffage",
                    models.CharField(
                        blank=True,
                        choices=[("oui", "oui"), ("non", "non")],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "stockage_indep",
                    models.CharField(
                        blank=True,
                        choices=[("oui", "oui"), ("non", "non")],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PointField(
                        null=True, srid=2154
                    ),
                ),
                (
                    "unite_pastorale",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="logements",
                        to="suivi_pasto.unitepastorale",
                    ),
                ),
            ],
            options={
                "verbose_name": "logement",
                "verbose_name_plural": "logements",
            },
        ),
        migrations.CreateModel(
            name="GeometrieUnitePastorale",
            fields=[
                ("created_by", models.CharField(blank=True, max_length=150, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("modified_on", models.DateTimeField(blank=True, null=True)),
                (
                    "id_geometrie_up",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=2154),
                ),
                ("date_debut_validite", models.DateField()),
                ("date_fin_validite", models.DateField(blank=True, null=True)),
                (
                    "unite_pastorale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="geometries",
                        to="suivi_pasto.unitepastorale",
                    ),
                ),
            ],
            options={
                "verbose_name": "géométrie d'unité pastorale",
                "verbose_name_plural": "géométries d'unités pastorales",
                "ordering": ["-date_debut_validite"],
            },
        ),
        migrations.CreateModel(
            name="EquipementAlpage",
            fields=[
                ("created_by", models.CharField(blank=True, max_length=150, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("modified_on", models.DateTimeField(blank=True, null=True)),
                (
                    "id_equipement_alpage",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("description", models.CharField(max_length=50)),
                ("etat", models.CharField(max_length=50)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True, null=True, srid=2154
                    ),
                ),
                (
                    "type_equipement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="eqptsAlpage",
                        to="suivi_pasto.typeequipement",
                    ),
                ),
                (
                    "unite_pastorale",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="eqptsAlpage",
                        to="suivi_pasto.unitepastorale",
                    ),
                ),
            ],
            options={
                "verbose_name": "équipement d'alpage",
                "verbose_name_plural": "équipements d'alpage",
            },
        ),
        migrations.CreateModel(
            name="ConventionDExploitation",
            fields=[
                ("created_by", models.CharField(blank=True, max_length=150, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("modified_on", models.DateTimeField(blank=True, null=True)),
                (
                    "id_convention",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "surface_location",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "surface_exploitable",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("date_debut", models.DateField(blank=True, null=True)),
                ("date_fin", models.DateField(blank=True, null=True)),
                ("effectif_bovin", models.IntegerField(blank=True, null=True)),
                ("effectif_ovin", models.IntegerField(blank=True, null=True)),
                ("effectif_caprin", models.IntegerField(blank=True, null=True)),
                ("effectif_porcin", models.IntegerField(blank=True, null=True)),
                ("debut_periode_expl", models.DateField(blank=True, null=True)),
                ("fin_periode_expl", models.DateField(blank=True, null=True)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True, null=True, srid=2154
                    ),
                ),
                (
                    "exploitant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conventions",
                        to="suivi_pasto.exploitant",
                    ),
                ),
                (
                    "type_convention",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conventions",
                        to="suivi_pasto.typeconvention",
                    ),
                ),
                (
                    "unite_pastorale",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conventions",
                        to="suivi_pasto.unitepastorale",
                    ),
                ),
            ],
            options={
                "verbose_name": "convention d'exploitation",
                "verbose_name_plural": "conventions d'exploitation",
            },
        ),
        migrations.AddConstraint(
            model_name="etrecompose",
            constraint=models.UniqueConstraint(
                condition=models.Q(("eleveur__isnull", False)),
                fields=("exploitant", "eleveur"),
                name="uq_etrecompose_exploitant_eleveur",
            ),
        ),
        migrations.AddConstraint(
            model_name="etrecompose",
            constraint=models.UniqueConstraint(
                condition=models.Q(("exploitant_membre__isnull", False)),
                fields=("exploitant", "exploitant_membre"),
                name="uq_etrecompose_exploitant_exploitant_membre",
            ),
        ),
        migrations.AddConstraint(
            model_name="etrecompose",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("eleveur__isnull", False), ("exploitant_membre__isnull", True)
                    ),
                    models.Q(
                        ("eleveur__isnull", True), ("exploitant_membre__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="chk_etrecompose_exactement_un_membre",
            ),
        ),
        migrations.AddConstraint(
            model_name="etrecompose",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("exploitant_membre__isnull", True),
                    models.Q(
                        ("exploitant_membre", models.F("exploitant")), _negated=True
                    ),
                    _connector="OR",
                ),
                name="chk_etrecompose_pas_autoreference",
            ),
        ),
        migrations.AddConstraint(
            model_name="beneficierde",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("date_fin__isnull", True),
                    ("date_debut__lte", models.F("date_fin")),
                    _connector="OR",
                ),
                name="chk_beneficier_de_dates_coherentes",
            ),
        ),
        migrations.AddConstraint(
            model_name="exploiter",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("date_fin__isnull", True),
                    ("date_debut__lte", models.F("date_fin")),
                    _connector="OR",
                ),
                name="chk_parcours_dates_coherentes",
            ),
        ),
        migrations.AddConstraint(
            model_name="exploiter",
            constraint=models.UniqueConstraint(
                fields=("cheptel", "quartier", "date_debut"),
                name="uniq_parcours_cheptel_quartier_debut",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="realisationmesure",
            unique_together={("mesure_plan", "situation")},
        ),
        migrations.AddConstraint(
            model_name="quartierpasto",
            constraint=models.UniqueConstraint(
                fields=("situation_exploitation", "code_quartier"),
                name="uniq_code_quartier_par_situation",
            ),
        ),
        migrations.AddConstraint(
            model_name="gardesituation",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("date_fin__isnull", True),
                    ("date_debut__lte", models.F("date_fin")),
                    _connector="OR",
                ),
                name="chk_garde_situation_dates_coherentes",
            ),
        ),
        migrations.AddConstraint(
            model_name="cheptel",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("date_fin__isnull", True),
                    ("date_debut__lte", models.F("date_fin")),
                    _connector="OR",
                ),
                name="chk_cheptel_dates_coherentes",
            ),
        ),
        migrations.AddConstraint(
            model_name="cheptel",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("eleveur__isnull", False),
                        ("exploitant_proprietaire__isnull", True),
                    ),
                    models.Q(
                        ("eleveur__isnull", True),
                        ("exploitant_proprietaire__isnull", False),
                    ),
                    models.Q(
                        ("eleveur__isnull", True),
                        ("exploitant_proprietaire__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="chk_cheptel_proprietaire_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="mesuredeplan",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("fin_periode__isnull", True),
                    ("debut_periode__lte", models.F("fin_periode")),
                    _connector="OR",
                ),
                name="chk_mesure_plan_periodes_coherentes",
            ),
        ),
        migrations.AddConstraint(
            model_name="situationdexploitation",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("date_fin__isnull", True),
                    ("date_debut__lte", models.F("date_fin")),
                    _connector="OR",
                ),
                name="chk_situation_dates_coherentes",
            ),
        ),
        migrations.AddConstraint(
            model_name="plandesuivi",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("date_fin__isnull", True),
                    ("date_debut__lte", models.F("date_fin")),
                    _connector="OR",
                ),
                name="chk_plan_suivi_dates_coherentes",
            ),
        ),
        migrations.AddConstraint(
            model_name="geometrieunitepastorale",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("date_fin_validite__isnull", True),
                    ("date_debut_validite__lte", models.F("date_fin_validite")),
                    _connector="OR",
                ),
                name="chk_geometrie_up_dates_coherentes",
            ),
        ),
        migrations.AddConstraint(
            model_name="conventiondexploitation",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("date_fin__isnull", True),
                    ("date_debut__lte", models.F("date_fin")),
                    _connector="OR",
                ),
                name="chk_convention_dates_coherentes",
            ),
        ),
        migrations.AddConstraint(
            model_name="conventiondexploitation",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("fin_periode_expl__isnull", True),
                    ("debut_periode_expl__lte", models.F("fin_periode_expl")),
                    _connector="OR",
                ),
                name="chk_convention_periodes_exploitation_coherentes",
            ),
        ),
    ]
