# Generated by Django 5.0.6 on 2026-06-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suivi_pasto", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="abridurgence",
            name="description",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="abridurgencecommodite",
            name="commentaire",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="berger",
            name="commentaire",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="categorieanimaux",
            name="description",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="categoriepension",
            name="description",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="cheptel",
            name="description",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="commodite",
            name="description",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="eleveur",
            name="commentaire",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="equipementalpage",
            name="description",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="espece",
            name="description",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="evenement",
            name="description",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="exploiter",
            name="commentaire",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="gardesituation",
            name="commentaire",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mesuredeplan",
            name="commentaire",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mesuredeplan",
            name="description",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="plandesuivi",
            name="description",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="production",
            name="description",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="proprietairefoncier",
            name="commentaire",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="race",
            name="description",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="ruche",
            name="description",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="subventionpnv",
            name="description",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="typeconvention",
            name="description",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="typedemesure",
            name="description",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="typedesuivi",
            name="description",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="typedexploitant",
            name="description",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="typeequipement",
            name="description",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="typeevenement",
            name="description",
            field=models.CharField(max_length=150),
        ),
    ]
