# Generated by Django 5.0.6 on 2026-06-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suivi_pasto", "0002_harmonize_description_commentaire"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="equipementalpage",
            name="description",
        ),
        migrations.RemoveField(
            model_name="equipementexploitant",
            name="description",
        ),
        migrations.RemoveField(
            model_name="ruche",
            name="description",
        ),
        migrations.RemoveField(
            model_name="subventionpnv",
            name="description",
        ),
        migrations.AddField(
            model_name="abridurgence",
            name="commentaire",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cheptel",
            name="commentaire",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="equipementalpage",
            name="commentaire",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="equipementexploitant",
            name="commentaire",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="evenement",
            name="commentaire",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="plandesuivi",
            name="commentaire",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ruche",
            name="commentaire",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subventionpnv",
            name="commentaire",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="evenement",
            name="description",
            field=models.CharField(default="", max_length=150),
            preserve_default=False,
        ),
    ]
