# Generated by Django 5.0.6 on 2026-06-01 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suivi_pasto", "0003_restructure_description_commentaire_v2"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Visite",
            fields=[
                ("created_by", models.CharField(blank=True, max_length=150, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("modified_on", models.DateTimeField(blank=True, null=True)),
                ("id_visite", models.BigAutoField(primary_key=True, serialize=False)),
                ("date_visite", models.DateField()),
                ("description", models.CharField(max_length=150)),
                ("commentaire", models.TextField(blank=True, null=True)),
                (
                    "contact_alpagiste",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visites_contact",
                        to="suivi_pasto.eleveur",
                    ),
                ),
                (
                    "observateurs",
                    models.ManyToManyField(
                        blank=True,
                        related_name="visites_observees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "unite_pastorale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visites",
                        to="suivi_pasto.unitepastorale",
                    ),
                ),
            ],
            options={
                "verbose_name": "visite",
                "verbose_name_plural": "visites",
                "ordering": ["-date_visite"],
            },
        ),
    ]
