# Generated by Django 5.0.6 on 2026-06-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suivi_pasto", "0004_visite"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="visite",
            name="contact_alpagiste",
        ),
        migrations.AddField(
            model_name="visite",
            name="contacts_alpagistes",
            field=models.ManyToManyField(
                blank=True, related_name="visites_contact", to="suivi_pasto.eleveur"
            ),
        ),
    ]
