# Generated by Django 5.0.6 on 2026-06-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suivi_pasto", "0005_visite_contacts_alpagistes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Enjeu",
            fields=[
                ("created_by", models.CharField(blank=True, max_length=150, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("modified_on", models.DateTimeField(blank=True, null=True)),
                ("id_enjeu", models.BigAutoField(primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=150)),
            ],
            options={
                "verbose_name": "enjeu",
                "verbose_name_plural": "enjeux",
                "ordering": ["description"],
            },
        ),
        migrations.AddField(
            model_name="mesuredeplan",
            name="enjeux",
            field=models.ManyToManyField(
                blank=True, related_name="mesures_de_plan", to="suivi_pasto.enjeu"
            ),
        ),
    ]
