# Generated by Django 5.0.6 on 2026-06-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suivi_pasto", "0010_quartierpasto_multipolygon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unitepastorale",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
