# Generated by Django 5.0.6 on 2026-06-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suivi_pasto", "0011_up_active_default_false"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoriepension",
            name="description",
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name="commodite",
            name="description",
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name="enjeu",
            name="description",
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name="espece",
            name="description",
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name="production",
            name="description",
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name="typeconvention",
            name="description",
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name="typedemesure",
            name="description",
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name="typedesuivi",
            name="description",
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name="typedexploitant",
            name="description",
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name="typeequipement",
            name="description",
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name="typeevenement",
            name="description",
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="categorieanimaux",
            unique_together={("description", "espece")},
        ),
        migrations.AlterUniqueTogether(
            name="race",
            unique_together={("description", "espece")},
        ),
    ]
