# Generated by Django 5.0.6 on 2026-06-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suivi_pasto", "0012_unique_nomenclatures_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="cheptel",
            name="nombre_animaux_exact",
            field=models.BooleanField(default=True),
        ),
    ]
