# Generated by Django 5.0.6 on 2026-06-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suivi_pasto", "0013_cheptel_nombre_animaux_exact"),
    ]

    operations = [
        migrations.AddField(
            model_name="typedemesure",
            name="types_suivi",
            field=models.ManyToManyField(
                blank=True, related_name="types_mesure", to="suivi_pasto.typedesuivi"
            ),
        ),
    ]
